@startmindmap
* Mi Semana

** Lunes
*** Trabajo
**** Reunión equipo (9:00)
**** Desarrollo feature (10:00-18:00)
*** Personal
**** Gimnasio (19:00)

** Martes
*** Trabajo
**** Code Review (9:00)
**** Sprint Planning (11:00)
*** Personal
**** Clase inglés (20:00)

** Miércoles
*** Trabajo
**** Desarrollo
**** Testing
*** Personal
**** Compras

left side

** Jueves
*** Trabajo
**** Reunión cliente
**** Documentación
*** Personal
**** Cine

** Viernes
*** Trabajo
**** Deploy
**** Retrospectiva
*** Personal
**** Cena amigos

** Fin de Semana
*** Sábado
**** Proyecto personal
**** Deporte
*** Domingo
**** Familia
**** Descanso

@endmindmap