@startmindmap
skinparam backgroundcolor transparent

- <:1F3AF:> Objetivos 2025

** <:1F4BC:> Carrera Profesional 
*** <:1F4C8:> Promoción a Senior 
**** <:1F393:> Certificación AWS
**** <:1F3C6:>  Liderar proyecto clave
**_ <:1F4B0:> Aumento salarial 20%
**_ <:1F310:> Trabajo remoto internacional

** <:1F4AA:> Salud & Fitness 
*** <:1F3C3:> Correr maratón 
**** <:1F4C5:> Entrenamiento 6 meses
**** <:1F3C5:> Completar en < 4h
**_ <:1F957:> Dieta equilibrada
**_ <:1F634:> Dormir 8h diarias

left side

** <:1F4DA:> Aprendizaje 
*** <:1F4BB:> Nuevas tecnologías 
**** <:269B:> React Native
**** <:1F980:> Rust programming 
***_ <:1F916:> Machine Learning
**_ <:1F5E3:> Idiomas 
*** <:1F1EC:> Inglés C1
*** <:1F1E9:> Alemán B1

** <:1F3E0:> Personal 
*** <:1F46A:> Familia 
**** <:1F389:> Vacaciones Europa
**** <:1F3AE:> Tiempo de calidad
*** <:1F4B8:> Finanzas
**** <:1F4B0:> Ahorrar 30% ingresos
**** <:1F4CA:> Inversiones diversificadas

@endmindmap